[general]
import = ["~/.config/alacritty/catppuccin/catppuccin-macchiato.toml"]

[window]
padding = { x = 5, y = 5 }
decorations = "buttonless"
opacity = 0.95

[font]
size = 12.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[cursor.style]
blinking = "On"

[[keyboard.bindings]]
key = "N"
mods = "Command"
action = "CreateNewWindow"

[[keyboard.bindings]]
key = "Right"
mods = "Alt"
chars = "\u001BF"

[[keyboard.bindings]]
key = "Left"
mods = "Alt"
chars = "\u001BB"
